// Code generated by MockGen. DO NOT EDIT.
// Source: ../service/balance.go

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockAccountService is a mock of AccountService interface
type MockAccountService struct {
	ctrl     *gomock.Controller
	recorder *MockAccountServiceMockRecorder
}

// MockAccountServiceMockRecorder is the mock recorder for MockAccountService
type MockAccountServiceMockRecorder struct {
	mock *MockAccountService
}

// NewMockAccountService creates a new mock instance
func NewMockAccountService(ctrl *gomock.Controller) *MockAccountService {
	mock := &MockAccountService{ctrl: ctrl}
	mock.recorder = &MockAccountServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockAccountService) EXPECT() *MockAccountServiceMockRecorder {
	return m.recorder
}

// Balance mocks base method
func (m *MockAccountService) Balance() float64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Balance")
	ret0, _ := ret[0].(float64)
	return ret0
}

// Balance indicates an expected call of Balance
func (mr *MockAccountServiceMockRecorder) Balance() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Balance", reflect.TypeOf((*MockAccountService)(nil).Balance))
}

// LockBalance mocks base method
func (m *MockAccountService) LockBalance() float64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LockBalance")
	ret0, _ := ret[0].(float64)
	return ret0
}

// LockBalance indicates an expected call of LockBalance
func (mr *MockAccountServiceMockRecorder) LockBalance() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LockBalance", reflect.TypeOf((*MockAccountService)(nil).LockBalance))
}

// UpdateBalance mocks base method
func (m *MockAccountService) UpdateBalance(newAmount float64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UpdateBalance", newAmount)
}

// UpdateBalance indicates an expected call of UpdateBalance
func (mr *MockAccountServiceMockRecorder) UpdateBalance(newAmount interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBalance", reflect.TypeOf((*MockAccountService)(nil).UpdateBalance), newAmount)
}

// UnlockBalance mocks base method
func (m *MockAccountService) UnlockBalance() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UnlockBalance")
}

// UnlockBalance indicates an expected call of UnlockBalance
func (mr *MockAccountServiceMockRecorder) UnlockBalance() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnlockBalance", reflect.TypeOf((*MockAccountService)(nil).UnlockBalance))
}
